// INGREDIENTS
export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAIL = 'GET_INGREDIENTS_FAIL';

export const CREATE_INGREDIENT_REQUEST = 'CREATE_INGREDIENT_REQUEST';
export const CREATE_INGREDIENT_SUCCESS = 'CREATE_INGREDIENT_SUCCESS';
export const CREATE_INGREDIENT_FAIL = 'CREATE_INGREDIENT_FAIL';

export const UPDATE_INGREDIENT_REQUEST = 'UPDATE_INGREDIENT_REQUEST';
export const UPDATE_INGREDIENT_SUCCESS = 'UPDATE_INGREDIENT_SUCCESS';
export const UPDATE_INGREDIENT_FAIL = 'UPDATE_INGREDIENT_FAIL';

export const DELETE_INGREDIENT_REQUEST = 'DELETE_INGREDIENT_REQUEST';
export const DELETE_INGREDIENT_SUCCESS = 'DELETE_INGREDIENT_SUCCESS';
export const DELETE_INGREDIENT_FAIL = 'DELETE_INGREDIENT_FAIL';

// TAGS
export const GET_TAGS_REQUEST = 'GET_TAGS_REQUEST';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_FAIL = 'GET_TAGS_FAIL';

export const CREATE_TAG_REQUEST = 'CREATE_TAG_REQUEST';
export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS';
export const CREATE_TAG_FAIL = 'CREATE_TAG_FAIL';

export const UPDATE_TAG_REQUEST = 'UPDATE_TAG_REQUEST';
export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';
export const UPDATE_TAG_FAIL = 'UPDATE_TAG_FAIL';

export const DELETE_TAG_REQUEST = 'DELETE_TAG_REQUEST';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const DELETE_TAG_FAIL = 'DELETE_TAG_FAIL';

// EQUIPMENTS
export const GET_EQUIPMENTS_REQUEST = 'GET_EQUIPMENTS_REQUEST';
export const GET_EQUIPMENTS_SUCCESS = 'GET_EQUIPMENTS_SUCCESS';
export const GET_EQUIPMENTS_FAIL = 'GET_EQUIPMENTS_FAIL';

export const CREATE_EQUIPMENT_REQUEST = 'CREATE_EQUIPMENT_REQUEST';
export const CREATE_EQUIPMENT_SUCCESS = 'CREATE_EQUIPMENT_SUCCESS';
export const CREATE_EQUIPMENT_FAIL = 'CREATE_EQUIPMENT_FAIL';

export const UPDATE_EQUIPMENT_REQUEST = 'UPDATE_EQUIPMENT_REQUEST';
export const UPDATE_EQUIPMENT_SUCCESS = 'UPDATE_EQUIPMENT_SUCCESS';
export const UPDATE_EQUIPMENT_FAIL = 'UPDATE_EQUIPMENT_FAIL';

export const DELETE_EQUIPMENT_REQUEST = 'DELETE_EQUIPMENT_REQUEST';
export const DELETE_EQUIPMENT_SUCCESS = 'DELETE_EQUIPMENT_SUCCESS';
export const DELETE_EQUIPMENT_FAIL = 'DELETE_EQUIPMENT_FAIL';
