// Plans
export const GET_PLANS_REQUEST = 'GET_PLANS_REQUEST';
export const GET_PLANS_SUCCESS = 'GET_PLANS_SUCCESS';
export const GET_PLANS_FAIL = 'GET_PLANS_FAIL';

export const CREATE_PLAN_REQUEST = 'CREATE_PLAN_REQUEST';
export const CREATE_PLAN_SUCCESS = 'CREATE_PLAN_SUCCESS';
export const CREATE_PLAN_FAIL = 'CREATE_PLAN_FAIL';

export const DELETE_PLAN_SUCCESS = "DELETE_PLAN_SUCCESS";
export const UPDATE_PLAN_DATE_SUCCESS = "UPDATE_PLAN_DATE_SUCCESS";
export const UPDATE_PLAN_SUCCESS = "UPDATE_PLAN_SUCCESS";

// Batch Sessions
export const GET_BATCH_SESSIONS_REQUEST = 'GET_BATCH_SESSIONS_REQUEST';
export const GET_BATCH_SESSIONS_SUCCESS = 'GET_BATCH_SESSIONS_SUCCESS';
export const GET_BATCH_SESSIONS_FAIL = 'GET_BATCH_SESSIONS_FAIL';

export const CREATE_BATCH_SESSION_SUCCESS = 'CREATE_BATCH_SESSION_SUCCESS';
export const DELETE_BATCH_SESSION_SUCCESS = 'DELETE_BATCH_SESSION_SUCCESS';
export const UPDATE_BATCH_SESSION_SUCCESS = 'UPDATE_BATCH_SESSION_SUCCESS';
