// Liste de toutes les recettes
export const GET_RECIPES_REQUEST = 'GET_RECIPES_REQUEST';
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
export const GET_RECIPES_FAIL = 'GET_RECIPES_FAIL';

// Détails d'une recette
export const GET_RECIPE_DETAIL_REQUEST = 'GET_RECIPE_DETAIL_REQUEST';
export const GET_RECIPE_DETAIL_SUCCESS = 'GET_RECIPE_DETAIL_SUCCESS';
export const GET_RECIPE_DETAIL_FAIL = 'GET_RECIPE_DETAIL_FAIL';

// Création d'une recette
export const CREATE_RECIPE_REQUEST = 'CREATE_RECIPE_REQUEST';
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_FAIL = 'CREATE_RECIPE_FAIL';

// Mise à jour d'une recette
export const UPDATE_RECIPE_REQUEST = 'UPDATE_RECIPE_REQUEST';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_FAIL = 'UPDATE_RECIPE_FAIL';
export const TOGGLE_UPDATE_RECIPE = "TOGGLE_UPDATE_RECIPE";
export const DUPLICATE_RECIPE_REQUEST = "DUPLICATE_RECIPE_REQUEST";
export const DUPLICATE_RECIPE_SUCCESS = "DUPLICATE_RECIPE_SUCCESS";
export const DUPLICATE_RECIPE_FAIL = "DUPLICATE_RECIPE_FAIL";

// Suppression d'une recette
export const DELETE_RECIPE_REQUEST = 'DELETE_RECIPE_REQUEST';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_FAIL = 'DELETE_RECIPE_FAIL';
