export const   GET_WEEKLY_CALORIES_REQUEST = "GET_WEEKLY_CALORIES_REQUEST"
export const   GET_WEEKLY_CALORIES_SUCCESS = "GET_WEEKLY_CALORIES_SUCCESS"
export const   GET_WEEKLY_CALORIES_FAIL = "GET_WEEKLY_CALORIES_FAIL"