export const   GET_WEEKLY_CALORIES_REQUEST = "GET_WEEKLY_CALORIES_REQUEST"
export const   GET_WEEKLY_CALORIES_SUCCESS = "GET_WEEKLY_CALORIES_SUCCESS"
export const   GET_WEEKLY_CALORIES_FAIL = "GET_WEEKLY_CALORIES_FAIL"

export const GET_WEEKLY_INGREDIENTS_REQUEST = "GET_WEEKLY_INGREDIENTS_REQUEST";
export const GET_WEEKLY_INGREDIENTS_SUCCESS = "GET_WEEKLY_INGREDIENTS_SUCCESS";
export const GET_WEEKLY_INGREDIENTS_FAIL = "GET_WEEKLY_INGREDIENTS_FAIL";

export const GET_GROCERY_LIST_REQUEST = "GET_GROCERY_LIST_REQUEST";
export const GET_GROCERY_LIST_SUCCESS = "GET_GROCERY_LIST_SUCCESS";
export const GET_GROCERY_LIST_FAIL = "GET_GROCERY_LIST_FAIL";
